### PR TITLE
Added Share button

### PR DESCRIPTION
**Pull request by punitm0**

### CODE REVIEW

**Comment by chamathpali** [comment]
@punit2502  can you remove your services json?

**Comment by punitm0** [comment]
I copied google-services.json from https://github.com/SurfEdge/flarum-mobile-android/pull/17 because without google-services.json config file Android studio is giving error

**Comment by punitm0** [comment]
But if you still want to delete it, I will delete it. Shoud I?

**Comment by Felli** [comment]
@chamathpali & @punit2502  I would recommend a temp `google-services.json`, it doesn't have to have anything in it just leave it blank, then allow the editor to place their own in to replace the temp.

**Comment by chamathpali** [comment]
@Felli yeah true. lets have a temp json

**Comment by chamathpali** [comment]
I made the google-services.json blank.

**Pull request merged**
